### ISSUE TITLE
Android: Production builds should not include Update functions

### ISSUE THREAD

**Issue by piotrowski** [bitstadium/cordova-plugin-hockeyapp#14]
Production builds should not include the UpdateActivity and also don't need the ExternalStorage permission afaik. There should be a way to disable these to be added to the Android project somehow.

As I am not yet totally clear on what actually has to be changed for release, I posted this question on the HockeyApp discussion board: http://support.hockeyapp.net/discussions/problems/49571-what-to-change-for-production-build-release

**Comment by piotrowski** [comment]
Okay, seems there is already some logic in HockeyApp that tries to take care of that:
https://github.com/bitstadium/HockeySDK-Android/blob/c8a379d0ae17da6e1e7bc835e2f76bb643da1bbb/src/main/java/net/hockeyapp/android/UpdateManager.java#L199-L216

**Comment by piotrowski** [comment]
Per the answer of the HockeyApp support staff we now also know what should _not_ be included in Android production builds:

> Android: You have to comment out, remove, or otherwise disable the line `UpdateManager.register`.

http://support.hockeyapp.net/discussions/problems/49571-what-to-change-for-production-build-release#comment_38526826

`UpdateManager.register` is `hockeyapp.checkForUpdate()` in this plugin.

**Comment by lostintangent** [comment]
The note you added in #15 seemed to have been removed, so I just added it back. I believe this note resolves this issue, since as you mentioned, the HockeyApp plugin only calls `UpdateManager.register` when `hockeyapp.checkForUpdate` is called, so we just need to make sure devs know not to call this in release builds.
